/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ContractThatRevertsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "reason"
      | "revertNoReason"
      | "revertWithReason"
      | "setReason"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "reason", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revertNoReason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revertWithReason",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setReason", values: [string]): string;

  decodeFunctionResult(functionFragment: "reason", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revertNoReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertWithReason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setReason", data: BytesLike): Result;
}

export interface ContractThatReverts extends BaseContract {
  connect(runner?: ContractRunner | null): ContractThatReverts;
  waitForDeployment(): Promise<this>;

  interface: ContractThatRevertsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  reason: TypedContractMethod<[], [string], "view">;

  revertNoReason: TypedContractMethod<[], [void], "view">;

  revertWithReason: TypedContractMethod<[reasonMsg: string], [void], "view">;

  setReason: TypedContractMethod<[reason: string], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "reason"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revertNoReason"
  ): TypedContractMethod<[], [void], "view">;
  getFunction(
    nameOrSignature: "revertWithReason"
  ): TypedContractMethod<[reasonMsg: string], [void], "view">;
  getFunction(
    nameOrSignature: "setReason"
  ): TypedContractMethod<[reason: string], [void], "nonpayable">;

  filters: {};
}
