/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ContractThatCallsPublicFunctionsInterface extends Interface {
  getFunction(
    nameOrSignature: "callGetBar" | "callGetFoo" | "callSetBar" | "callSetFoo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callGetBar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callGetFoo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callSetBar",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callSetFoo",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "callGetBar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callGetFoo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callSetBar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "callSetFoo", data: BytesLike): Result;
}

export interface ContractThatCallsPublicFunctions extends BaseContract {
  connect(runner?: ContractRunner | null): ContractThatCallsPublicFunctions;
  waitForDeployment(): Promise<this>;

  interface: ContractThatCallsPublicFunctionsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callGetBar: TypedContractMethod<
    [contractAddress: AddressLike],
    [bigint],
    "view"
  >;

  callGetFoo: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  callSetBar: TypedContractMethod<
    [contractAddress: AddressLike, bar: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  callSetFoo: TypedContractMethod<
    [contractAddress: AddressLike, foo: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callGetBar"
  ): TypedContractMethod<[contractAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "callGetFoo"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "callSetBar"
  ): TypedContractMethod<
    [contractAddress: AddressLike, bar: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callSetFoo"
  ): TypedContractMethod<
    [contractAddress: AddressLike, foo: string],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
