/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC1271Wallet } from "./MockERC1271Wallet";
export type { MockERC1271WalletReturningBytes32 } from "./MockERC1271WalletReturningBytes32";
export type { MockERC1271WalletWithCustomValidation } from "./MockERC1271WalletWithCustomValidation";
export type { MockStateModifyingERC1271Wallet } from "./MockStateModifyingERC1271Wallet";
