/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FiatTokenUtilInterface extends Interface {
  getFunction(
    nameOrSignature: "transferWithMultipleAuthorizations"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransferFailed"): EventFragment;

  encodeFunctionData(
    functionFragment: "transferWithMultipleAuthorizations",
    values: [BytesLike, BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "transferWithMultipleAuthorizations",
    data: BytesLike
  ): Result;
}

export namespace TransferFailedEvent {
  export type InputTuple = [authorizer: AddressLike, nonce: BytesLike];
  export type OutputTuple = [authorizer: string, nonce: string];
  export interface OutputObject {
    authorizer: string;
    nonce: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FiatTokenUtil extends BaseContract {
  connect(runner?: ContractRunner | null): FiatTokenUtil;
  waitForDeployment(): Promise<this>;

  interface: FiatTokenUtilInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  transferWithMultipleAuthorizations: TypedContractMethod<
    [params: BytesLike, signatures: BytesLike, atomic: boolean],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "transferWithMultipleAuthorizations"
  ): TypedContractMethod<
    [params: BytesLike, signatures: BytesLike, atomic: boolean],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "TransferFailed"
  ): TypedContractEvent<
    TransferFailedEvent.InputTuple,
    TransferFailedEvent.OutputTuple,
    TransferFailedEvent.OutputObject
  >;

  filters: {
    "TransferFailed(address,bytes32)": TypedContractEvent<
      TransferFailedEvent.InputTuple,
      TransferFailedEvent.OutputTuple,
      TransferFailedEvent.OutputObject
    >;
    TransferFailed: TypedContractEvent<
      TransferFailedEvent.InputTuple,
      TransferFailedEvent.OutputTuple,
      TransferFailedEvent.OutputObject
    >;
  };
}
