/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  AbstractUpgraderHelper,
  AbstractUpgraderHelperInterface,
} from "../../../../../contracts/v2/upgrader/helpers/AbstractUpgraderHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "fiatTokenProxy",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proxy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tearDown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class AbstractUpgraderHelper__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractUpgraderHelperInterface {
    return new Interface(_abi) as AbstractUpgraderHelperInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AbstractUpgraderHelper {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as AbstractUpgraderHelper;
  }
}
