/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockERC1271WalletReturningBytes32,
  MockERC1271WalletReturningBytes32Interface,
} from "../../../../contracts/test/MockERC1271Wallet.sol/MockERC1271WalletReturningBytes32";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "isValidSignature",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610174806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80631626ba7e14610030575b600080fd5b6100dd6004803603604081101561004657600080fd5b8135919081019060408101602082013564010000000081111561006857600080fd5b82018360208201111561007a57600080fd5b8035906020019184600183028401116401000000008311171561009c57600080fd5b91908080601f016020809104026020016040519081016040528093929190818152602001838380828437600092019190915250929550610112945050505050565b604080517fffffffff000000000000000000000000000000000000000000000000000000009092168252519081900360200190f35b60007fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff60005260206000f3fea2646970667358221220fbbf6495ded638bc3394c0a62bf0833b8c610a20fc6ffc9faa90198e1f5c193164736f6c634300060c0033";

type MockERC1271WalletReturningBytes32ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockERC1271WalletReturningBytes32ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockERC1271WalletReturningBytes32__factory extends ContractFactory {
  constructor(...args: MockERC1271WalletReturningBytes32ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockERC1271WalletReturningBytes32 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockERC1271WalletReturningBytes32__factory {
    return super.connect(runner) as MockERC1271WalletReturningBytes32__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockERC1271WalletReturningBytes32Interface {
    return new Interface(_abi) as MockERC1271WalletReturningBytes32Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockERC1271WalletReturningBytes32 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockERC1271WalletReturningBytes32;
  }
}
